### ISSUE TITLE
gf doesn't work properly with maven project

### ISSUE THREAD

**Issue by mrroman** [tpope/vim-classpath#5]
I've noticed that incorrect source path (with wrong number of asterisks) is inserted in 
front of path variable (in autoload/classpath.vim). It looks like this currently:

```
 83       let base = escape(root.sep.'src'.sep.'*'.sep.'*', ', ') . ','
```

and I think it should be 

```
 83       let base = escape(root.sep.'src'.sep.'*'.sep.'**', ', ') . ','
```

to cover subfolder of packages.

**Comment by benknoble** [comment]
I'd like to re-open this discussion a bit: `gf` currently does work on qualified names, but `:find` is practically useless with only `src/*/*`—even typing the full filename out (which, IIUC, `:find` is to help me avoid) gives "file not found on 'path'" (E345). `gf` on a non-qualified name, such as a class in the current project, is also useless.

Granted, I have tags working well-enough for java, but I would like to also have `gf`/`:find`/`:dsearch`/`:isearch` working, and they (AFAIK) all rely on `path` being set well. (I know I need to set `define` and `include`/`includeexpr` to make the latter two work, but that's not really germane here.)

**Comment by tpope** [comment]
To start with, see my take on the purpose of `'path'` in the [Apathy README](https://github.com/tpope/vim-apathy).

If your goal is to make `gf` on `SomeClass` in a file with `import some.namespace.*` find `src/main/java/some/namespace/SomeClass.java`, there are a few approaches you could take:

* On file load, parse out the `import` declarations, and add a path like `src/*/*/some/namespace` for each `import` wildcard. This is out of scope for classpath.vim, as my interest and ability stops at the JVM and this is a language specific solution.
* Remap `gf` to handle import resolution. This is my preferred technique: I use it in rails.vim and Fireplace among other places.  Also out of scope for classpath.vim.
* Change `'path'` to use `**` globs, so that Vim finds _any_ file named `SomeClass.java` buried at any level of the directory hierarchy. To which I say NO, absolutely not. Use a fuzzy finder if this is what you want.

**Comment by benknoble** [comment]
@tpope thanks for the comments; they've given me some ideas (parsing package declarations would actually probably be enough for my java use cases). I hadn't considered the limited scope of classpath, so that makes sense.
